export const clubLogos: { [key: string]: string } = {
  "AJ Auxerre": "/_assets/teamlogos/logoauxerre.svg",
  "Paris Saint-Germain FC": "/_assets/teamlogos/logoparissg.svg",
  "Olympique de Marseille": "/_assets/teamlogos/logomarseille.svg",
  "Stade Brestois 29": "/_assets/teamlogos/logobrest.svg",
  "Le Havre AC": "/_assets/teamlogos/logolehavre.svg",
  "Racing Club de Lens": "/_assets/teamlogos/logolens.svg",
  "Toulouse FC": "/_assets/teamlogos/logotoulouse.svg",
  "Olympique Lyonnais": "/_assets/teamlogos/logolyon.svg",
  "AS Saint-Étienne": "/_assets/teamlogos/logostetienne.svg",
  "Lille OSC": "/_assets/teamlogos/logolille.svg",
  "Stade Rennais FC 1901": "/_assets/teamlogos/logorennes.svg",
  "FC Nantes": "/_assets/teamlogos/logonantes.svg",
  "Angers SCO": "/_assets/teamlogos/logoangers.svg",
  "AS Monaco FC": "/_assets/teamlogos/logomonaco.svg",
  "OGC Nice": "/_assets/teamlogos/logonice.svg",
  "Montpellier HSC": "/_assets/teamlogos/logomontpellier.svg",
  "Stade de Reims": "/_assets/teamlogos/logostadedereims.svg",
  "RC Strasbourg Alsace": "/_assets/teamlogos/logostrasbourg.svg",
};

export const formatName: { [key: string]: string } = {
  "AJ Auxerre": "AJA",
  "Paris Saint-Germain FC": "PSG",
  "Olympique de Marseille": "OM",
  "Stade Brestois 29": "SB29",
  "Le Havre AC": "HAC",
  "Racing Club de Lens": "RCL",
  "Toulouse FC": "TFC",
  "Olympique Lyonnais": "OL",
  "AS Saint-Étienne": "ASSE",
  "Lille OSC": "LOSC",
  "Stade Rennais FC 1901": "SRFC",
  "FC Nantes": "NAN",
  "Angers SCO": "SCO",
  "AS Monaco FC": "ASM",
  "OGC Nice": "OGCN",
  "Montpellier HSC": "MHSC",
  "Stade de Reims": "SDR",
  "RC Strasbourg Alsace": "RSCA",
};
