export const teamsNames = [
  {
    namesList: ["Paris SG", "PSG", "Paris Saint-Germain"],
    actualName: "Paris SG",
    abr: "PSG",
    logo: "logoparissg.svg",
  },
  {
    namesList: ["Ol. Lyonnais", "Olympique Lyonnais", "Lyon"],
    actualName: "Ol. Lyonnais",
    abr: "OL",
    logo: "logolyon.svg",
  },
  {
    namesList: ["Marseille", "Olympique de Marseille", "OM"],
    actualName: "Marseille",
    abr: "OM",
    logo: "logomarseille.svg",
  },
  {
    namesList: ["Monaco", "AS Monaco"],
    actualName: "Monaco",
    abr: "ASM",
    logo: "logomonaco.svg",
  },
  {
    namesList: [
      "R. Strasbourg",
      "Strasbourg",
      "Racing Club Strasbourg",
      "Racing Club de Strasbourg",
      "RC Strasbourg Alsace",
      "Racing Club Strasbourg Alsace",
    ],
    actualName: "Strasbourg",
    abr: "RCSA",
    logo: "logostrasbourg.svg",
  },
  {
    namesList: ["LOSC Lille", "Lille OSC", "Lille"],
    actualName: "LOSC Lille",
    abr: "LOSC",
    logo: "logolille.svg",
  },
  {
    namesList: ["RC Lens", "Racing Club de Lens", "Lens"],
    actualName: "RC Lens",
    abr: "RCL",
    logo: "logolens.svg",
  },
  {
    namesList: ["Paris FC", "PFC"],
    actualName: "Paris FC",
    abr: "PFC",
    logo: "logoparisfc.svg",
  },
  {
    namesList: ["Stade Rennais", "Stade Rennais FC", "Rennes"],
    actualName: "Stade Rennais",
    abr: "SRFC",
    logo: "logorennes.svg",
  },
  {
    namesList: ["Stade Brestois", "Brest", "Stade Brestois 29", "SB29"],
    actualName: "Stade Brestois",
    abr: "SB29",
    logo: "logobrest.svg",
  },
  {
    namesList: ["Toulouse", "Toulouse FC", "TFC"],
    actualName: "Toulouse",
    abr: "TFC",
    logo: "logotoulouse.svg",
  },
  {
    namesList: ["OGC Nice", "Nice"],
    actualName: "OGC Nice",
    abr: "OGCN",
    logo: "logonice.svg",
  },
  {
    namesList: ["FC Lorient", "Lorient", "FC Lorient Bretagne Sud", "FCL"],
    actualName: "FC Lorient",
    abr: "FCL",
    logo: "logolorient.svg",
  },
  {
    namesList: ["AJ Auxerre", "Auxerre", "AJA"],
    actualName: "AJ Auxerre",
    abr: "AJA",
    logo: "logoauxerre.svg",
  },
  {
    namesList: ["Le Havre AC", "Le Havre", "LHAC"],
    actualName: "Le Havre AC",
    abr: "HAC",
    logo: "logolehavre.svg",
  },
  {
    namesList: ["FC Nantes", "Nantes", "FCN"],
    actualName: "FC Nantes",
    abr: "FCN",
    logo: "logonantes.svg",
  },
  {
    namesList: ["Angers SCO", "Angers", "SCO Angers"],
    actualName: "Angers SCO",
    abr: "SCO",
    logo: "logoangers.svg",
  },
  {
    namesList: ["FC Metz", "Metz", "FCM"],
    actualName: "FC Metz",
    abr: "FCM",
    logo: "logometz.svg",
  },
];
