export const CitationData = [
    {
        id: 1,
        bannerImage: "/_assets/citationsbanners/id1.webp",
        person: "Guy Roux",
        role: "Entraineur",
        citation: "Je n'ai jamais demandé un centime d'augmentation au président Hamel en quarante ans. Je lui disais juste : 'Président, l'inflation est de tant cette année', et il ajustait.",
        personPicture: "/_assets/methodeexpertpp/guyroux.jpg",
    },
    {
        id: 2,
        bannerImage: "/_assets/citationsbanners/id2.jpg",
        person: "Basile Boli",
        role: "Joueur (1983-1990)",
        citation: "Un soir, je voulais sortir en douce. Je me suis caché dans le coffre de la voiture d'un copain pour passer le portail du centre de formation. Mais Guy Roux a arrêté la voiture, a toqué sur le coffre et a dit : 'Basile, tu peux sortir, je sais que tu es là.'",
        personPicture: "/_assets/methodeexpertpp/basileboli.jpg",
    },
    {
        id: 3,
        bannerImage: "/_assets/citationsbanners/id3.jpg",
        person: "Jean-Claude Hamel",
        role: "Président",
        citation: "C'est un vieux couple. On s'engueule, mais on ne divorce jamais.",
        personPicture: "/_assets/methodeexpertpp/jeanclaudehamel.jpg",
    },
    {
        id: 4,
        bannerImage: "/_assets/citationsbanners/id4.jpg",
        person: "Djibril Cissé",
        role: "Joueur (1999-2004)",
        citation: "Auxerre, c'est ma maison. C'est là que je suis devenu un homme. Guy Roux a été comme un second père pour moi. Il m'a appris à gérer mon argent, ma carrière et ma vie.",
        personPicture: "/_assets/methodeexpertpp/djibrilcisse.avif",
    },
    {
        id: 5,
        bannerImage: "/_assets/citationsbanners/id5.jpeg",
        person: "Eric Cantona",
        role: "Joueur (1983-1988)",
        citation: "À Auxerre, on t'apprend le football, mais on t'apprend surtout à ne pas te prendre pour un autre.",
        personPicture: "/_assets/methodeexpertpp/ericcantona.jpeg",
    },
    {
        id: 6,
        bannerImage: "/_assets/citationsbanners/id6.jpg",
        person: "Guy Roux",
        role: "Entraineur",
        citation: "Le maintien, c'est 42 points. Tant qu'on ne les a pas, on ne parle pas d'Europe.",
        personPicture: "/_assets/methodeexpertpp/guyroux.jpg",
    },
    {
        id: 7,
        bannerImage: "/_assets/citationsbanners/id7.jpg",
        person: "Gérard Bourgoin",
        role: "Président",
        citation: "Nous sommes les Gaulois du football français. On résiste, on se bat avec nos armes, et parfois, le petit village fait tomber l'Empire romain.",
        personPicture: "/_assets/methodeexpertpp/gerardbourgoin.jpg",
    },
    {
        id: 8,
        bannerImage: "/_assets/citationsbanners/id8.avif",
        person: "Benoît Pedretti",
        role: "Joueur (2006-2011)",
        citation: "On nous avait prédit le ventre mou, on a fini dans les étoiles. C'est ça, la magie d'Auxerre.",
        personPicture: "/_assets/methodeexpertpp/benoitpedretti.webp",
    },
    {
        id: 9,
        bannerImage: "/_assets/citationsbanners/id9.jpeg",
        person: "Yann Lachuer",
        role: "Joueur (1993-1998, 2001-2006)",
        citation: "Cette coupe, c'est la victoire de l'amitié. On n'est peut-être pas les meilleurs joueurs de France, mais on est la meilleure bande de potes.",
        personPicture: "/_assets/methodeexpertpp/yannlachuer.jpg",
    },
    {
        id: 10,
        bannerImage: "/_assets/citationsbanners/id10.jpeg",
        person: "Gauthier Hein",
        role: "Joueur (2020-2024)",
        citation: "Ailleurs, il y a la pression de l'argent. À Auxerre, il y a la pression de l'histoire. Quand tu portes ce maillot, tu sens le poids des légendes sur tes épaules, et ça te donne des ailes.",
        personPicture: "/_assets/methodeexpertpp/gauthierhein.jpg",
    },
    {
        id: 11,
        bannerImage: "/_assets/citationsbanners/id11.webp",
        person: "Guy Roux",
        role: "Entraineur",
        citation: "J'avais passé un accord avec les videurs des boîtes de nuit de la région. Ils m'appelaient si un de mes joueurs se pointait. En échange, je leur filais des places pour les matchs. C'était du donnant-donnant.",
        personPicture: "/_assets/methodeexpertpp/guyroux.jpg",
    },
    {
        id: 12,
        bannerImage: "/_assets/citationsbanners/id12.webp",
        person: "Guy Roux",
        role: "Entraineur",
        citation: "J'allais voir le colonel avec des bouteilles de vin. Je lui disais : 'Mon colonel, la patrie a besoin de soldats, mais l'AJA a besoin de marquer des buts'. Et Éric était libéré pour le match.",
        personPicture: "/_assets/methodeexpertpp/guyroux.jpg",
    },
]